### ISSUE TITLE
Getting different results based on punctuation

### ISSUE THREAD

**Issue by stefan-falk** [jitsi/asr-wer#10]
Is this intended behavior?

```python
print(wer('hello', 'hello.'))
print(wer('hello', 'hello!'))
```

Gives

```
0.0
1.0
```

**Comment by nikvaessen** [comment]
No, when I worked on this the speech-to-text engine I used did not add insert `!` or `?`. I will add it to the list of characters which are filtered out.

**Comment by stefan-falk** [comment]
@nikvaessen imho this should not happen at all - or it should be possible to disable this behavior. 

`wer()` should take an iterable and calculate the WER based on those elements. The input should not be modified any further - also no lower-casing. Imho one should not assume that this is what the caller of `wer()` wants. It's the callers responsibility to pass in preprocessed input.

**Comment by nikvaessen** [comment]
Thanks for this input. I've updated the library so that it's easier for users to control what per-processing is done,
