### ISSUE TITLE
Pypi version outdated

### ISSUE THREAD

**Issue by FerrariDG** [jitsi/asr-wer#5]
After the fix on PR #4 the Pypi version is outdated.

**Comment by saghul** [comment]
What Pypi version? Do you men the pip version? Python version?

**Comment by FerrariDG** [comment]
Yes, for the installation via `pip install jiwer`.
https://pypi.org/project/jiwer/#history

**Comment by saghul** [comment]
You mean a new release on pypi is necesary? (ping @nikvaessen )

**Comment by FerrariDG** [comment]
Yes, there is a workaround by installing using the git repo `pip install git+https://github.com/jitsi/asr-wer`, but if you use `pip install jirew` will install the version without the fix on PR #4.

**Comment by nikvaessen** [comment]
I've now bumped the version on pipy to 1.3.1

**Comment by FerrariDG** [comment]
Thanks, btw awesome package 😃 !!!
