### ISSUE TITLE
WIL and MER

### ISSUE THREAD

**Issue by MiniXC** [jitsi/asr-wer#9]
Additionally to WER, WIL (Word Information Lost) and MER (Match Error Rate), can be good performance measures for ASR. I could not find any pypi packages that support those measures, and think they might be a good fit for **jiwer**.

See:
- [Automatic Speech Recognition
Errors Detection and Correction: A Review](https://www.researchgate.net/profile/Rahhal_Errattahi/publication/324427003_Automatic_Speech_Recognition_Errors_Detection_and_Correction_A_Review/links/5ad462590f7e9b2859365080/Automatic-Speech-Recognition-Errors-Detection-and-Correction-A-Review.pdf)
- [From WER and RIL to MER and WIL: improved evaluation
measures for connected speech recognition](https://pdfs.semanticscholar.org/8516/531ff3bd874b66b811f0bd4e21a2d6b10e54.pdf)

I'd be happy to open a pull request with those measures added, I you think they could fit this package.

**Comment by nikvaessen** [comment]
Feel free to make a PR :)

**Comment by bartvanandel** [comment]
@MiniXC Did you ever get around to do some coding for this? I'd be interested to use these measures too.
